// ============================================================
// ANIME AUCTION: ARENA — Character Database
// Power-scaled to real anime canon (peak/final forms)
// ============================================================

const CHARACTER_DB = [
    // ========== X-TIER ($20-$25) — Omniversal / Gods ==========
    {
        id: 101,
        name: "Featherine Augustus Aurora",
        series: "Umineko When They Cry",
        tier: "X",
        baseCost: 25,
        emoji: "📖",
        color: "#FFFFFF",
        atk: 999,
        def: 999,
        spd: 999,
        sp: 999,
        hp: 999,
        tags: ["Creator", "Witch", "Omnipotent"],
        ultimate: "Script of Reality",
        ultimateDesc: "She writes the plot itself — erases you from existence with a thought!",
        ultimateMultiplier: 10.0,
    },
    {
        id: 102,
        name: "Anti-Spiral",
        series: "Gurren Lagann",
        tier: "X",
        baseCost: 20,
        emoji: "🌌",
        color: "#000000",
        atk: 250,
        def: 250,
        spd: 250,
        sp: 250,
        hp: 500,
        tags: ["Cosmic", "Villain", "Abstract"],
        ultimate: "Infinity Big Bang Storm",
        ultimateDesc: "Throws literal galaxies like shurikens to crush hope!",
        ultimateMultiplier: 5.0,
    },
    {
        id: 103,
        name: "Anos Voldigoad",
        series: "The Misfit of Demon King Academy",
        tier: "X",
        baseCost: 20,
        emoji: "👑",
        color: "#4B0082",
        atk: 220,
        def: 200,
        spd: 200,
        sp: 250,
        hp: 400,
        tags: ["Demon King", "Reincarnated", "Overpowered"],
        ultimate: "Venuzdonoa",
        ultimateDesc: "The logic-destroying sword — kills you even if you are immortal!",
        ultimateMultiplier: 4.5,
    },
    {
        id: 104,
        name: "Sailor Cosmos",
        series: "Sailor Moon",
        tier: "X",
        baseCost: 20,
        emoji: "✨",
        color: "#FFD700",
        atk: 200,
        def: 220,
        spd: 250,
        sp: 250,
        hp: 450,
        tags: ["Cosmic", "Hero", "Time Traveler"],
        ultimate: "Lambda Power",
        ultimateDesc: "Resets and recreates the entire universe!",
        ultimateMultiplier: 4.0,
    },
    {
        id: 105,
        name: "The Truth",
        series: "Fullmetal Alchemist",
        tier: "X",
        baseCost: 20,
        emoji: "👁️",
        color: "#E0E0E0",
        atk: 150,
        def: 300,
        spd: 150,
        sp: 300,
        hp: 600,
        tags: ["God", "Abstract", "Alchemist"],
        ultimate: "The Gate",
        ultimateDesc: "I am you, you are me — taking your alchemy and your existence!",
        ultimateMultiplier: 4.0,
    },
    {
        id: 99,
        name: "Rimuru Tempest",
        series: "That Time I Got Reincarnated as a Slime",
        tier: "X",
        baseCost: 20,
        emoji: "💧",
        color: "#00BCD4",
        atk: 180,
        def: 200,
        spd: 190,
        sp: 250,
        hp: 400,
        tags: ["Slime", "Demon Lord", "Isekai"],
        ultimate: "Azathoth, Lord of the Void",
        ultimateDesc: "Consumes all matter and energy — absolute control over time and space!",
        ultimateMultiplier: 4.0,
    },

    // ========== SSS-TIER ($12-$15) — Universe / Planet Busters ==========
    {
        id: 1,
        name: "Goku",
        series: "Dragon Ball Z",
        tier: "SSS",
        baseCost: 15,
        emoji: "🟠",
        color: "#FF8C00",
        atk: 98,
        def: 85,
        spd: 97,
        sp: 95,
        hp: 180,
        tags: ["Saiyan", "Martial Artist", "Transformation"],
        ultimate: "Mastered Ultra Instinct",
        ultimateDesc: "Transcends mortal limits — dodges and counters everything automatically!",
        ultimateMultiplier: 3.0,
    },
    {
        id: 5,
        name: "Vegeta",
        series: "Dragon Ball Z",
        tier: "SSS",
        baseCost: 14,
        emoji: "💪",
        color: "#3498DB",
        atk: 96,
        def: 78,
        spd: 92,
        sp: 90,
        hp: 170,
        tags: ["Saiyan", "Martial Artist", "Transformation"],
        ultimate: "Ultra Ego: Hakai",
        ultimateDesc: "Gets stronger the more damage he takes — destroys matter itself!",
        ultimateMultiplier: 2.8,
    },
    {
        id: 44,
        name: "Frieza",
        series: "Dragon Ball Z",
        tier: "SSS",
        baseCost: 15,
        emoji: "👾",
        color: "#C084FC",
        atk: 97,
        def: 82,
        spd: 90,
        sp: 88,
        hp: 175,
        tags: ["Villain", "Transformation", "Emperor"],
        ultimate: "Black Frieza: Annihilation",
        ultimateDesc: "Surpasses Ultra Instinct & Ultra Ego — one-shots gods!",
        ultimateMultiplier: 3.2,
    },
    {
        id: 42,
        name: "Saitama",
        series: "One Punch Man",
        tier: "SSS",
        baseCost: 15,
        emoji: "👊",
        color: "#FDE047",
        atk: 100,
        def: 100,
        spd: 98,
        sp: 30,
        hp: 250,
        tags: ["Hero", "Martial Artist", "Bald"],
        ultimate: "Serious Punch²",
        ultimateDesc: "A punch so powerful it splits the observable universe in half!",
        ultimateMultiplier: 5.0,
    },
    {
        id: 11,
        name: "Beast Gohan",
        series: "Dragon Ball Super",
        tier: "SSS",
        baseCost: 14,
        emoji: "🔥",
        color: "#9C27B0",
        atk: 97,
        def: 88,
        spd: 93,
        sp: 90,
        hp: 175,
        tags: ["Saiyan", "Human", "Transformation"],
        ultimate: "Special Beam Cannon",
        ultimateDesc: "A ferocious evolution of his hidden power — planet-shattering beam!",
        ultimateMultiplier: 2.9,
    },
    {
        id: 106,
        name: "Yhwach",
        series: "Bleach",
        tier: "SSS",
        baseCost: 15,
        emoji: "👁️‍🗨️",
        color: "#000000",
        atk: 100,
        def: 95,
        spd: 90,
        sp: 100,
        hp: 195,
        tags: ["Quincy", "Villain", "God"],
        ultimate: "The Almighty",
        ultimateDesc: "Sees and alters all possible futures — defeats you before you even attack!",
        ultimateMultiplier: 3.5,
    },
    {
        id: 2,
        name: "Naruto",
        series: "Naruto Shippuden",
        tier: "SSS",
        baseCost: 14,
        emoji: "🍥",
        color: "#FF6B00",
        atk: 92,
        def: 78,
        spd: 95,
        sp: 92,
        hp: 160,
        tags: ["Ninja", "Jinchuriki", "Sage"],
        ultimate: "Baryon Mode",
        ultimateDesc: "Fuses chakra at a nuclear level — overwhelming power at the cost of life force!",
        ultimateMultiplier: 3.0,
    },
    {
        id: 6,
        name: "Sasuke",
        series: "Naruto Shippuden",
        tier: "S",
        baseCost: 4,
        emoji: "⚡",
        color: "#8E44AD",
        atk: 86,
        def: 78,
        spd: 90,
        sp: 82,
        hp: 145,
        tags: ["Ninja", "Sharingan", "Swordsman"],
        ultimate: "Indra's Arrow",
        ultimateDesc: "Combines Susanoo with lightning chakra for a devastating final strike.",
        ultimateMultiplier: 2.6,
    },
    {
        id: 100,
        name: "Sung Jinwoo",
        series: "Solo Leveling",
        tier: "SSS",
        baseCost: 15,
        emoji: "🗡️",
        color: "#673AB7",
        atk: 99,
        def: 90,
        spd: 98,
        sp: 95,
        hp: 190,
        tags: ["Shadow Monarch", "Hunter", "Necromancer"],
        ultimate: "Arise: Shadow Army",
        ultimateDesc: "Summons millions of immortal shadow soldiers to obliterate everything!",
        ultimateMultiplier: 3.2,
    },

    // ========== S-TIER ($9-$11) — Continental / Country Level ==========
    {
        id: 45,
        name: "Madara",
        series: "Naruto Shippuden",
        tier: "S",
        baseCost: 11,
        emoji: "🌀",
        color: "#7C3AED",
        atk: 95,
        def: 88,
        spd: 85,
        sp: 95,
        hp: 180,
        tags: ["Ninja", "Sharingan", "Villain"],
        ultimate: "Infinite Tsukuyomi",
        ultimateDesc: "Ten Tails Jinchuriki casts an illusion over the entire world!",
        ultimateMultiplier: 3.0,
    },
    {
        id: 107,
        name: "Cosmic Garou",
        series: "One Punch Man",
        tier: "S",
        baseCost: 11,
        emoji: "🌌",
        color: "#4F46E5",
        atk: 97,
        def: 90,
        spd: 95,
        sp: 98,
        hp: 175,
        tags: ["Villain", "Martial Artist", "Cosmic"],
        ultimate: "Gamma Ray Burst",
        ultimateDesc: "Channels the energy of a dying star — absolute atomic destruction!",
        ultimateMultiplier: 3.2,
    },
    {
        id: 3,
        name: "Luffy",
        series: "One Piece",
        tier: "S",
        baseCost: 10,
        emoji: "👒",
        color: "#E74C3C",
        atk: 90,
        def: 72,
        spd: 88,
        sp: 85,
        hp: 165,
        tags: ["Pirate", "Rubber", "Haki User"],
        ultimate: "Gear 5: Bajrang Gun",
        ultimateDesc: "Sun God Nika punches with an island-sized fist that warps reality!",
        ultimateMultiplier: 2.8,
    },
    {
        id: 4,
        name: "Ichigo",
        series: "Bleach",
        tier: "S",
        baseCost: 10,
        emoji: "⚔️",
        color: "#F39C12",
        atk: 94,
        def: 70,
        spd: 93,
        sp: 88,
        hp: 155,
        tags: ["Shinigami", "Swordsman", "Hollow"],
        ultimate: "True Bankai: Gran Rey Getsuga",
        ultimateDesc: "Shinigami + Hollow + Quincy merged — a slash that cuts dimensions!",
        ultimateMultiplier: 2.8,
    },
    {
        id: 21,
        name: "Gojo",
        series: "Jujutsu Kaisen",
        tier: "S",
        baseCost: 10,
        emoji: "👁️‍🗨️",
        color: "#60A5FA",
        atk: 88,
        def: 99,
        spd: 90,
        sp: 98,
        hp: 140,
        tags: ["Sorcerer", "Sensei", "Six Eyes"],
        ultimate: "Unlimited Void",
        ultimateDesc: "Infinity makes him untouchable — traps enemies in infinite information!",
        ultimateMultiplier: 2.8,
    },
    {
        id: 23,
        name: "Sukuna",
        series: "Jujutsu Kaisen",
        tier: "S",
        baseCost: 10,
        emoji: "😈",
        color: "#DC2626",
        atk: 96,
        def: 80,
        spd: 88,
        sp: 95,
        hp: 165,
        tags: ["Curse", "Villain", "Sorcerer"],
        ultimate: "Malevolent Shrine",
        ultimateDesc: "Full 20-finger domain — guaranteed-hit slashes that shred everything!",
        ultimateMultiplier: 3.0,
    },
    {
        id: 35,
        name: "Meruem",
        series: "Hunter x Hunter",
        tier: "S",
        baseCost: 10,
        emoji: "🐜",
        color: "#65A30D",
        atk: 97,
        def: 95,
        spd: 88,
        sp: 85,
        hp: 190,
        tags: ["Chimera Ant", "King", "Villain"],
        ultimate: "Post-Rose: Rage Blast",
        ultimateDesc: "Absorbed Nen abilities — the most powerful being in the world!",
        ultimateMultiplier: 3.0,
    },
    {
        id: 28,
        name: "Muzan",
        series: "Demon Slayer",
        tier: "B",
        baseCost: 5,
        emoji: "🩸",
        color: "#7F1D1D",
        atk: 88,
        def: 75,
        spd: 82,
        sp: 85,
        hp: 220,
        tags: ["Demon", "Villain", "Progenitor"],
        ultimate: "Final Form: Biokinesis",
        ultimateDesc: "Near-immortal progenitor — regenerates from anything, body becomes a weapon!",
        ultimateMultiplier: 2.5,
    },
    {
        id: 29,
        name: "Eren",
        series: "Attack on Titan",
        tier: "S",
        baseCost: 9,
        emoji: "🦹",
        color: "#059669",
        atk: 85,
        def: 95,
        spd: 35,
        sp: 90,
        hp: 280,
        tags: ["Titan", "Soldier", "Transformation"],
        ultimate: "Founding Titan: The Rumbling",
        ultimateDesc: "Commands millions of Colossal Titans to flatten the entire world!",
        ultimateMultiplier: 3.5,
    },

    // ========== A-TIER ($6-$8) — City / Town Level ==========
    {
        id: 7,
        name: "Zoro",
        series: "One Piece",
        tier: "A",
        baseCost: 8,
        emoji: "🗡️",
        color: "#27AE60",
        atk: 90,
        def: 68,
        spd: 78,
        sp: 75,
        hp: 145,
        tags: ["Pirate", "Swordsman", "Haki User"],
        ultimate: "King of Hell: Ashura",
        ultimateDesc: "Advanced Conqueror's Haki three-sword demon form — cuts mountains!",
        ultimateMultiplier: 2.5,
    },
    {
        id: 10,
        name: "Kakashi",
        series: "Naruto Shippuden",
        tier: "A",
        baseCost: 7,
        emoji: "📖",
        color: "#95A5A6",
        atk: 82,
        def: 72,
        spd: 88,
        sp: 88,
        hp: 125,
        tags: ["Ninja", "Sharingan", "Sensei"],
        ultimate: "DMS Kamui Shuriken",
        ultimateDesc: "Double Mangekyo Susanoo — warps and slices across dimensions!",
        ultimateMultiplier: 2.5,
    },
    {
        id: 32,
        name: "Gon",
        series: "Hunter x Hunter",
        tier: "A",
        baseCost: 7,
        emoji: "✊",
        color: "#16A34A",
        atk: 95,
        def: 60,
        spd: 90,
        sp: 85,
        hp: 135,
        tags: ["Hunter", "Nen User", "Enhancer"],
        ultimate: "Adult Gon: Jajanken",
        ultimateDesc: "Sacrifices all potential — transforms into a Meruem-level monster!",
        ultimateMultiplier: 3.0,
    },
    {
        id: 33,
        name: "Killua",
        series: "Hunter x Hunter",
        tier: "A",
        baseCost: 7,
        emoji: "⚡",
        color: "#818CF8",
        atk: 78,
        def: 55,
        spd: 96,
        sp: 82,
        hp: 110,
        tags: ["Hunter", "Nen User", "Assassin"],
        ultimate: "Godspeed: Lightning Palm",
        ultimateDesc: "Moves and reacts at the speed of lightning — untouchable assassin!",
        ultimateMultiplier: 2.5,
    },
    {
        id: 49,
        name: "Jotaro",
        series: "JoJo's Bizarre Adventure",
        tier: "A",
        baseCost: 7,
        emoji: "🧢",
        color: "#6366F1",
        atk: 85,
        def: 72,
        spd: 78,
        sp: 92,
        hp: 120,
        tags: ["Stand User", "Martial Artist", "Time Stop"],
        ultimate: "Star Platinum: The World",
        ultimateDesc: "Stops time for 5 seconds — ORA ORA ORA ORA ORA!",
        ultimateMultiplier: 2.5,
    },
    {
        id: 50,
        name: "Dio",
        series: "JoJo's Bizarre Adventure",
        tier: "A",
        baseCost: 7,
        emoji: "🧛",
        color: "#CA8A04",
        atk: 82,
        def: 75,
        spd: 76,
        sp: 90,
        hp: 140,
        tags: ["Stand User", "Villain", "Time Stop"],
        ultimate: "The World Over Heaven",
        ultimateDesc: "Rewrites reality itself with a single punch! WRYYYYY!",
        ultimateMultiplier: 2.8,
    },
    {
        id: 34,
        name: "Hisoka",
        series: "Hunter x Hunter",
        tier: "A",
        baseCost: 6,
        emoji: "🃏",
        color: "#E11D48",
        atk: 80,
        def: 58,
        spd: 82,
        sp: 88,
        hp: 115,
        tags: ["Hunter", "Nen User", "Villain"],
        ultimate: "Bungee Gum: Post-Mortem Nen",
        ultimateDesc: "Revived by his own Nen — properties of both rubber AND gum!",
        ultimateMultiplier: 2.2,
    },
    {
        id: 13,
        name: "Sanji",
        series: "One Piece",
        tier: "A",
        baseCost: 6,
        emoji: "🔥",
        color: "#E67E22",
        atk: 82,
        def: 68,
        spd: 90,
        sp: 70,
        hp: 130,
        tags: ["Pirate", "Martial Artist", "Cook"],
        ultimate: "Ifrit Jambe: Boeuf Burst",
        ultimateDesc: "Germa exoskeleton + blue flames — kicks that melt steel!",
        ultimateMultiplier: 2.3,
    },
    {
        id: 15,
        name: "Byakuya",
        series: "Bleach",
        tier: "A",
        baseCost: 6,
        emoji: "🌸",
        color: "#E91E8B",
        atk: 82,
        def: 72,
        spd: 82,
        sp: 80,
        hp: 125,
        tags: ["Shinigami", "Swordsman", "Noble"],
        ultimate: "Senbonzakura: Ikka Senjinkei",
        ultimateDesc: "True Bankai — one hundred million blade petals fill the sky!",
        ultimateMultiplier: 2.3,
    },
    {
        id: 47,
        name: "Toshiro",
        series: "Bleach",
        tier: "A",
        baseCost: 6,
        emoji: "❄️",
        color: "#22D3EE",
        atk: 80,
        def: 72,
        spd: 82,
        sp: 82,
        hp: 125,
        tags: ["Shinigami", "Swordsman", "Elemental"],
        ultimate: "Mature Bankai: Shikai Hyōketsu",
        ultimateDesc: "Adult form freezes matter at a molecular level — absolute zero!",
        ultimateMultiplier: 2.3,
    },
    {
        id: 37,
        name: "Roy Mustang",
        series: "Fullmetal Alchemist",
        tier: "A",
        baseCost: 6,
        emoji: "🔥",
        color: "#1D4ED8",
        atk: 82,
        def: 48,
        spd: 68,
        sp: 85,
        hp: 100,
        tags: ["Alchemist", "State", "Elemental"],
        ultimate: "Flame Alchemy: Pinpoint Incinerate",
        ultimateDesc: "Snaps his fingers — boils the moisture in your eyes!",
        ultimateMultiplier: 2.5,
    },

    // ========== B-TIER ($3-$5) — Building / Street Level ==========
    {
        id: 22,
        name: "Itadori",
        series: "Jujutsu Kaisen",
        tier: "B",
        baseCost: 5,
        emoji: "👊",
        color: "#F472B6",
        atk: 78,
        def: 52,
        spd: 82,
        sp: 70,
        hp: 120,
        tags: ["Sorcerer", "Vessel", "Martial Artist"],
        ultimate: "Black Flash Combo",
        ultimateDesc: "Spatial distortion punches — 2.5x cursed energy impact!",
        ultimateMultiplier: 2.3,
    },
    {
        id: 25,
        name: "Tanjiro",
        series: "Demon Slayer",
        tier: "B",
        baseCost: 5,
        emoji: "🌊",
        color: "#06B6D4",
        atk: 75,
        def: 62,
        spd: 78,
        sp: 75,
        hp: 118,
        tags: ["Slayer", "Swordsman", "Sun Breather"],
        ultimate: "Sun Breathing: 13th Form",
        ultimateDesc: "All 12 forms chained into one — the ultimate Demon Slayer technique!",
        ultimateMultiplier: 2.5,
    },
    {
        id: 27,
        name: "Rengoku",
        series: "Demon Slayer",
        tier: "B",
        baseCost: 5,
        emoji: "🔥",
        color: "#F97316",
        atk: 78,
        def: 68,
        spd: 75,
        sp: 72,
        hp: 125,
        tags: ["Slayer", "Swordsman", "Hashira"],
        ultimate: "Esoteric Art: Ninth Form — Rengoku",
        ultimateDesc: "The Flame Hashira's final technique — a blazing dragon of willpower!",
        ultimateMultiplier: 2.3,
    },
    {
        id: 12,
        name: "Rock Lee",
        series: "Naruto",
        tier: "B",
        baseCost: 4,
        emoji: "🦵",
        color: "#2ECC71",
        atk: 85,
        def: 35,
        spd: 95,
        sp: 50,
        hp: 100,
        tags: ["Ninja", "Martial Artist", "Taijutsu"],
        ultimate: "Eight Gates: Gate of Death",
        ultimateDesc: "Opens all 8 gates — becomes faster than light but risks death!",
        ultimateMultiplier: 3.0,
    },
    {
        id: 36,
        name: "Edward Elric",
        series: "Fullmetal Alchemist",
        tier: "B",
        baseCost: 4,
        emoji: "⚗️",
        color: "#EAB308",
        atk: 65,
        def: 58,
        spd: 75,
        sp: 85,
        hp: 100,
        tags: ["Alchemist", "Martial Artist", "State"],
        ultimate: "Philosopher's Stone Transmutation",
        ultimateDesc: "Claps hands — reshapes the battlefield into a weapon!",
        ultimateMultiplier: 2.2,
    },
    {
        id: 41,
        name: "Genos",
        series: "One Punch Man",
        tier: "B",
        baseCost: 4,
        emoji: "🤖",
        color: "#F59E0B",
        atk: 82,
        def: 42,
        spd: 82,
        sp: 65,
        hp: 85,
        tags: ["Cyborg", "Hero", "Martial Artist"],
        ultimate: "10-Second Mode: Incinerate",
        ultimateDesc: "Overclocks his core for 10 seconds — city-leveling firepower!",
        ultimateMultiplier: 2.5,
    },
    {
        id: 26,
        name: "Zenitsu",
        series: "Demon Slayer",
        tier: "B",
        baseCost: 3,
        emoji: "⚡",
        color: "#FACC15",
        atk: 70,
        def: 30,
        spd: 95,
        sp: 72,
        hp: 82,
        tags: ["Slayer", "Swordsman", "Thunder"],
        ultimate: "7th Form: Flaming Thunder God",
        ultimateDesc: "His own original technique — a thunderbolt dragon slash!",
        ultimateMultiplier: 2.5,
    },

];

const CHARACTER_BALANCE = {
    101: ["X", 300, 48, 36, 70, 20, 3.0, "Author's Rewrite", "undoHit", "Once per fight, undo one hit by restoring its damage as HP."],
    102: ["X", 300, 50, 38, 55, 20, 3.0, "Spiral Nemesis", "halveUltimate", "Takes half damage from enemy ultimates."],
    103: ["X", 290, 49, 38, 62, 20, 3.0, "Creation Magic: Time Rewind", "ignore25Def", "Ignores 25% of enemy DEF."],
    99: ["X", 290, 46, 38, 60, 20, 3.0, "Azathoth: Void Annihilation", "stealAtk", "Steals 10% of enemy ATK each turn."],
    104: ["X", 280, 40, 36, 65, 20, 2.8, "Silver Crystal Cosmos Blast", "regen5", "Heals 5% of max HP each turn."],
    105: ["X", 270, 44, 40, 40, 15, 3.0, "Gate of Truth: Equivalent Exchange", "stealDef", "Steals 3 DEF from the enemy per hit."],
    106: ["SSS", 250, 42, 30, 55, 18, 2.6, "Almighty: Rewrite the Future", "foresight", "Has a 25% chance to dodge on turn 1."],
    42: ["SSS", 240, 42, 30, 62, 20, 3.0, "Serious Punch", "growAtk2", "Gains 2 ATK each turn."],
    1: ["SSS", 240, 41, 29, 66, 18, 2.7, "Ultra Instinct Kamehameha", "gokuDodge", "Automatically dodges while below 40% HP."],
    5: ["SSS", 230, 39, 28, 60, 17, 2.6, "Final Flash", "buffOnHit2", "Gains 2 ATK each time he is hit."],
    44: ["SSS", 220, 36, 27, 62, 16, 2.5, "Death Ball", "lowerDef2", "Lowers enemy DEF by 2 each turn."],
    11: ["SSS", 235, 40, 28, 60, 17, 2.7, "Beast Cannon", "lowHpAtk6", "Gains 6 ATK once below 35% HP."],
    2: ["SSS", 235, 38, 28, 58, 18, 2.6, "Six Paths Rasenshuriken", "dodge15", "Has a 15% chance to dodge."],
    6: ["SSS", 225, 39, 26, 66, 17, 2.6, "Indra's Arrow", "negateHit", "Once per fight, negates one incoming hit."],
    100: ["SSS", 230, 40, 27, 64, 18, 2.6, "Monarch's Domain: Shadow Army", "revive20", "Once per fight, revives at 20% HP."],
    107: ["S", 200, 35, 24, 68, 18, 2.5, "Cosmic Copy Burst", "copyDamage", "Copies the damage of the enemy's last hit."],
    23: ["S", 200, 35, 22, 62, 18, 2.6, "Malevolent Shrine", "ignore20Def", "Ignores 20% of enemy DEF."],
    45: ["S", 195, 34, 24, 56, 16, 2.5, "Perfect Susanoo Meteor", "regen4", "Heals 4% of max HP each turn."],
    21: ["S", 190, 34, 22, 70, 17, 2.7, "Hollow Purple", "negateHit", "Infinity negates the first incoming hit."],
    3: ["S", 200, 32, 22, 64, 15, 2.5, "Gear 5 Bajrang Gun", "reduceDamage15", "Takes 15% less damage."],
    4: ["S", 185, 33, 22, 64, 16, 2.6, "Final Getsuga Tenshou", "buffAtk3", "Gains 5 ATK for 3 turns, once per fight."],
    29: ["S", 200, 31, 26, 45, 14, 2.8, "Rumbling Titan Stomp", "regen6", "Regenerates 6 HP each turn."],
    35: ["S", 175, 33, 22, 66, 15, 2.4, "Royal Fury Barrage", "buffDefOnHit", "Gains 1 DEF after every hit taken."],
    7: ["A", 160, 28, 20, 56, 14, 2.2, "Asura Ichibugin", "secondSlash", "Has a 20% chance to land a second hit."],
    15: ["A", 140, 26, 16, 62, 14, 2.4, "Senkei Senbonzakura Kageyoshi", "dodge12", "Has a 12% chance to dodge."],
    13: ["A", 145, 27, 15, 64, 13, 2.2, "Diable Jambe Hell Memories", "burn3", "Burns the enemy for 3 HP per turn for 3 turns."],
    50: ["A", 150, 27, 18, 60, 15, 2.5, "The World: Road Roller", "skipTurn", "Once per fight, skips the enemy's next attack."],
    49: ["A", 150, 27, 18, 58, 15, 2.4, "Star Platinum: The World", "doubleHit15", "Has a 15% chance to land a double hit."],
    47: ["A", 135, 25, 16, 62, 13, 2.3, "Daiguren Hyorinmaru", "slow10", "Lowers enemy SPD by 10."],
    10: ["A", 140, 25, 15, 58, 14, 2.3, "Kamui Raikiri", "repeatDamage", "Once per fight, repeats the enemy's last damage."],
    33: ["A", 130, 25, 14, 72, 14, 2.2, "Godspeed Lightning Palm", "dodge15", "Has a 15% chance to dodge."],
    32: ["A", 135, 27, 14, 58, 14, 2.6, "Jajanken Rock (Adult Form)", "glassCannon", "Takes 10% extra damage."],
    34: ["A", 130, 24, 14, 60, 13, 2.3, "Bungee Gum Barrage", "slow8", "Lowers enemy SPD by 8."],
    37: ["A", 130, 24, 14, 52, 13, 2.4, "Flame Alchemy Hellfire", "burn3", "Burns the enemy for 3 HP per turn for 3 turns."],
    28: ["B", 120, 22, 14, 54, 14, 2.2, "Blood Demon Tendril Storm", "regen5", "Regenerates 5 HP each turn."],
    22: ["B", 115, 21, 13, 56, 14, 2.4, "Black Flash", "crit25", "Has a 20% chance to deal 25% extra damage."],
    25: ["B", 110, 20, 12, 52, 14, 2.3, "Hinokami Kagura", "buffOnHit2", "Gains 2 ATK each time he is hit."],
    41: ["B", 110, 20, 14, 50, 12, 2.3, "Incineration Cannon", "growAtk1", "Gains 1 ATK each turn."],
    27: ["B", 110, 20, 12, 54, 14, 2.3, "Ninth Form: Purgatory", "burn3", "Burns the enemy for 3 HP per turn for 3 turns."],
    12: ["B", 105, 22, 10, 68, 12, 2.6, "Eight Gates: Hirudora", "eightGates", "Gains 6 ATK and loses 5 HP each turn."],
    26: ["B", 100, 20, 10, 70, 13, 2.4, "Thunderclap Flash", "crit50", "Has a 20% chance to deal 50% extra damage."],
    36: ["B", 105, 18, 12, 54, 12, 2.2, "Clap Transmutation Blade", "buffDef4", "Gains 4 DEF for 2 turns, once per fight."],
};

CHARACTER_DB.forEach(char => {
    const balance = CHARACTER_BALANCE[char.id];
    if (!balance) return;
    const [tier, hp, atk, def, spd, sp, ultimateMultiplier, ultimate, abilityKey, abilityDesc] = balance;
    Object.assign(char, { tier, hp, atk, def, sp, spd, ultimateMultiplier, ultimate, abilityKey, abilityDesc });
});

// Canon power levels (×1,000 scale) and fair auction prices ($30 budget)
const CHAR_ECONOMY = {
    101: { powerLevel: 50000, baseCost: 20 },
    102: { powerLevel: 46000, baseCost: 18 },
    103: { powerLevel: 44000, baseCost: 17 },
    99:  { powerLevel: 42000, baseCost: 16 },
    104: { powerLevel: 40000, baseCost: 15 },
    105: { powerLevel: 38000, baseCost: 14 },
    106: { powerLevel: 24000, baseCost: 9 },
    42:  { powerLevel: 23000, baseCost: 9 },
    1:   { powerLevel: 22000, baseCost: 8 },
    100: { powerLevel: 20000, baseCost: 7 },
    2:   { powerLevel: 20000, baseCost: 7 },
    6:   { powerLevel: 10000, baseCost: 4 },
    5:   { powerLevel: 19000, baseCost: 7 },
    11:  { powerLevel: 18000, baseCost: 6 },
    44:  { powerLevel: 17000, baseCost: 6 },
    107: { powerLevel: 15000, baseCost: 6 },
    23:  { powerLevel: 15000, baseCost: 6 },
    45:  { powerLevel: 14000, baseCost: 5.5 },
    21:  { powerLevel: 14000, baseCost: 5.5 },
    3:   { powerLevel: 13000, baseCost: 5 },
    4:   { powerLevel: 12000, baseCost: 4.5 },
    29:  { powerLevel: 12000, baseCost: 4.5 },
    35:  { powerLevel: 11000, baseCost: 4 },
    7:   { powerLevel: 9000, baseCost: 3.5 },
    15:  { powerLevel: 8000, baseCost: 3 },
    13:  { powerLevel: 8000, baseCost: 3 },
    50:  { powerLevel: 8000, baseCost: 3 },
    49:  { powerLevel: 7000, baseCost: 2.5 },
    47:  { powerLevel: 7000, baseCost: 2.5 },
    10:  { powerLevel: 7000, baseCost: 2.5 },
    33:  { powerLevel: 6000, baseCost: 2 },
    32:  { powerLevel: 6000, baseCost: 2 },
    34:  { powerLevel: 5000, baseCost: 2 },
    37:  { powerLevel: 5000, baseCost: 2 },
    28:  { powerLevel: 4000, baseCost: 1.5 },
    22:  { powerLevel: 4000, baseCost: 1.5 },
    25:  { powerLevel: 3000, baseCost: 1 },
    41:  { powerLevel: 3000, baseCost: 1 },
    27:  { powerLevel: 3000, baseCost: 1 },
    12:  { powerLevel: 2000, baseCost: 1 },
    26:  { powerLevel: 2000, baseCost: 1 },
    36:  { powerLevel: 2000, baseCost: 1 },
};

CHARACTER_DB.forEach(char => {
    const econ = CHAR_ECONOMY[char.id];
    if (econ) {
        char.powerLevel = econ.powerLevel;
        char.baseCost = econ.baseCost;
    }
});

const TIER_PRICE_RANGES = {
    X: [20, 25],
    SSS: [12, 15],
    S: [9, 11],
    A: [6, 8],
    B: [3, 5],
};

Object.entries(TIER_PRICE_RANGES).forEach(([tier, [minimum, maximum]]) => {
    const tierCharacters = CHARACTER_DB
        .filter(char => char.tier === tier)
        .sort((left, right) => right.powerLevel - left.powerLevel);
    tierCharacters.forEach((char, index) => {
        const rank = tierCharacters.length > 1 ? index / (tierCharacters.length - 1) : 0;
        char.baseCost = Math.round((maximum - rank * (maximum - minimum)) * 2) / 2;
    });
});

function formatMoney(amount) {
    return Number.isInteger(amount) ? `$${amount}` : `$${amount.toFixed(2)}`;
}

function getCharacterPowerLevel(char) {
    return char.powerLevel ?? 0;
}

// ============================================================
// SYNERGY DEFINITIONS
// ============================================================

const SYNERGIES = [
    {
        name: "Saiyan Pride",
        requiredTag: "Saiyan",
        requiredCount: 2,
        bonus: { atk: 12, def: 5 },
        description: "2+ Saiyans: ATK +12, DEF +5 for all Saiyans",
        icon: "🔥",
    },
    {
        name: "Shadow Village",
        requiredTag: "Ninja",
        requiredCount: 2,
        bonus: { spd: 15, sp: 5 },
        description: "2+ Ninjas: SPD +15, SP +5 for all Ninjas",
        icon: "🌀",
    },
    {
        name: "Straw Hat Crew",
        requiredTag: "Pirate",
        requiredCount: 2,
        bonus: { atk: 8, hp: 20 },
        description: "2+ Pirates: ATK +8, HP +20 for all Pirates",
        icon: "☠️",
    },
    {
        name: "Hero Academy",
        requiredTag: "Hero",
        requiredCount: 2,
        bonus: { def: 10, sp: 10 },
        description: "2+ Heroes: DEF +10, SP +10 for all Heroes",
        icon: "🦸",
    },
    {
        name: "Soul Society",
        requiredTag: "Shinigami",
        requiredCount: 2,
        bonus: { atk: 10, spd: 10 },
        description: "2+ Shinigami: ATK +10, SPD +10 for all Shinigami",
        icon: "💀",
    },
    {
        name: "Blade Masters",
        requiredTag: "Swordsman",
        requiredCount: 2,
        bonus: { atk: 10, spd: 5 },
        description: "2+ Swordsmen: ATK +10, SPD +5 for all Swordsmen",
        icon: "⚔️",
    },
    {
        name: "Martial Arts Tournament",
        requiredTag: "Martial Artist",
        requiredCount: 2,
        bonus: { atk: 5, def: 5, spd: 5 },
        description: "2+ Martial Artists: ATK/DEF/SPD +5 for all Martial Artists",
        icon: "🥋",
    },
    {
        name: "Cursed Energy",
        requiredTag: "Sorcerer",
        requiredCount: 2,
        bonus: { atk: 10, sp: 12 },
        description: "2+ Sorcerers: ATK +10, SP +12 — Cursed energy flows!",
        icon: "🔮",
    },
    {
        name: "Demon Slayer Corps",
        requiredTag: "Slayer",
        requiredCount: 2,
        bonus: { atk: 10, spd: 10 },
        description: "2+ Slayers: ATK +10, SPD +10 — Breathing techniques sync!",
        icon: "🌊",
    },
    {
        name: "Survey Corps",
        requiredTag: "Soldier",
        requiredCount: 2,
        bonus: { spd: 12, atk: 8 },
        description: "2+ Soldiers: SPD +12, ATK +8 — Wings of Freedom!",
        icon: "🦅",
    },
    {
        name: "Hunter License",
        requiredTag: "Hunter",
        requiredCount: 2,
        bonus: { atk: 8, spd: 8, sp: 8 },
        description: "2+ Hunters: ATK/SPD/SP +8 — Licensed to fight!",
        icon: "🎫",
    },
    {
        name: "Equivalent Exchange",
        requiredTag: "Alchemist",
        requiredCount: 2,
        bonus: { atk: 12, def: 12 },
        description: "2 Alchemists: ATK +12, DEF +12 — The law of alchemy!",
        icon: "⚗️",
    },
    {
        name: "Stand Proud",
        requiredTag: "Stand User",
        requiredCount: 2,
        bonus: { atk: 12, sp: 12 },
        description: "2 Stand Users: ATK +12, SP +12 — Stand power resonates!",
        icon: "🌟",
    },
    {
        name: "League of Villains",
        requiredTag: "Villain",
        requiredCount: 2,
        bonus: { atk: 15, sp: 8 },
        description: "2+ Villains: ATK +15, SP +8 — Evil knows no bounds!",
        icon: "💀",
    },
    {
        name: "Elemental Masters",
        requiredTag: "Elemental",
        requiredCount: 2,
        bonus: { atk: 10, sp: 10 },
        description: "2+ Elementals: ATK +10, SP +10 — Nature's fury unleashed!",
        icon: "🌪️",
    },
];

if (typeof module !== "undefined" && module.exports) {
    module.exports = { CHARACTER_DB };
}
